### ISSUE TITLE
GPL License missing

### ISSUE THREAD

**Issue by marcel-licence** [GillesLACAUD/OPLA-Source-code#1]
Please ensure that licence information is also put into this project (like the origin of some the sources).
Thank you!

**Comment by GillesLACAUD** [comment]
Hi Marcel.
I have add the licence file.
Is it correct now or i must also add some text in the source code ?

**Comment by marcel-licence** [comment]
Hi Gilles, 
thank you very much!
Regarding the source files, I don't know at the moment but I will check if some update would be useful. In that case I think I will prepare a pull request.

**Comment by GillesLACAUD** [comment]
Thx Marcel :-)
